---
image:
  pullPolicy: Always
  tag: "0.1.0-rc"

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: rc.example.local
      paths:
        - /

service:
  # set to NodePort for minikube
  type: NodePort

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi